# Based on https://gitlab.com/humaid/yabfig/blob/master/.gitlab-ci.yml by Humaid
image: golang:latest

variables:
  REPO_NAME: gitlab.com/group-nacdlow/official-plugins/light-mode
  BINARY: light-mode

before_script:
  - cd $CI_PROJECT_DIR

stages:
    - get
    - test
    - build

format:
    stage: test
    script:
      - go fmt ./...
      - go vet ./...
      - go test -cover -race ./...

compile:
    stage: build
    script:
      - go build -buildmode=plugin -o $CI_PROJECT_DIR/$BINARY
    artifacts:
      paths:
        - $BINARY


